services:
  lighttpd:
    build: .
    volumes:
      - ${PWD}/index.html:/var/www/html/index.html
    ports:
      - "80:80"
    networks:
      - web_server
  test-health:
    image: quay.io/curl/curl:latest
    command: >
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
networks:
  web_server:
