services:
  lighttpd:
    build: .
    volumes:
      - ${PWD}/index.html:/var/www/html/index.html
      - ${PWD}/index.html:/var/www/html/plain.html
      - ${PWD}/auth.conf:/etc/lighttpd/conf.d/auth.conf
      - ${PWD}/lighttpd.user:/etc/lighttpd/lighttpd.user
    ports:
      - "80:80"
    networks:
      - web_server
  test-no-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent --show-error lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-no-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer "
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-not-b64-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer token"
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-b64-fake-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer dG9rZW4="
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-b64-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
networks:
  web_server:
