services:
  lighttpd:
    build: .
    volumes:
      - ${PWD}/index.html:/var/www/html/index.html
      - ${PWD}/index.html:/var/www/html/plain.html
      - ${PWD}/auth.conf:/etc/lighttpd/conf.d/auth.conf
      - ${PWD}/lighttpd.user:/etc/lighttpd/lighttpd.user
    ports:
      - "80:80"
    networks:
      - web_server
  test-no-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent --show-error lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-no-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer "
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-not-b64-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer token"
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-b64-fake-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer dG9rZW4="
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
  test-bearer-b64-token:
    image: quay.io/curl/curl:latest
    command: >
      --silent
      --show-error
      -H "Authorization: Bearer ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lJeE1qTTBOVFkzT0Rrd0lpd2libUZ0WlNJNklrcHZhRzRnUkc5bElpd2lhV0YwSWpveE5URTJNak01TURJeWZRLlNmbEt4d1JKU01lS0tGMlFUNGZ3cE1lSmYzNlBPazZ5SlZfYWRRc3N3NWM="
      lighttpd:80
    networks:
      - web_server
    depends_on:
      lighttpd:
        condition: service_started
networks:
  web_server:
